version: "3"
services:
  db:
    image: mariadb
    container_name: "docker_calender_db"
    restart: always
    ports:
      - 3308:3308
    command: --port 3308
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calenderdb
      TZ: "Asia/Tokyo"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000
